### ISSUE TITLE
Save sgf files?

### ISSUE THREAD

**Issue by pliuphys** [zhanzhenzhen/go-engine-tester#1]
I tried to run the program in Windows and it seems to work. That's great! It seems gomill doesn't support Windows.

I don't see sgf files being saved, and saw no discussion in the readme about it. I assume there's no support yet?

Also it would be nice to write results to a file, preferably with the score/resignation. Currently the summary only says color&winner (0 Winner: first b).

Thank you.

**Comment by zhanzhenzhen** [comment]
Actually, I also wanted to print SGF, but Leela Zero has a bug:

https://github.com/gcp/leela-zero/issues/1875

As soon as the author has merged the fix into next branch, I'll support printing SGF rather than printing `play b <point> play w <point> ...` and may add a config option to save SGF files.

For now, if you want to view a single game in Sabaki, there's a workaround:

1. Copy `play b <point> play w <point> ...` that has been generated at the end of the game to the clipboard.
2. Enter the Leela Zero command line.
3. Paste it.
4. Type printsgf.
5. Save the SGF to a file.

**Comment by pliuphys** [comment]
Thanks!

**Comment by zhanzhenzhen** [comment]
Just found out that `printsgf` is a Leela-only GTP command. So I now think I'd better implement SGF on my own.

**Comment by zhanzhenzhen** [comment]
The new version prints SGF to console. You can copy and paste to make SGF files. It doesn't have an option to save to file directly. This is just a small work and I don't want to make it complicated.
